### ISSUE TITLE
Unable to connect: XChaCha20 is not defined

### ISSUE THREAD

**Issue by PFGimenez** [Rabbit-Company/Passky-Website#10]
Hello,

I am using https://vault.passky.org/ with server https://eu1.passky.org. I cannot access my passwords, even though my login/password is correct.

To Reproduce: try to login on https://eu1.passky.org. I don’t know if this affects other servers.

![passky issue](https://user-images.githubusercontent.com/11853513/208056399-65890624-852c-436a-b71c-de23e30c577f.png)

This screenshot also includes some errors in the console:
Uncaught ReferenceError: initStorageCache is not defined
    <anonymous> https://vault.passky.org/js/passwords.js:1
Uncaught ReferenceError: XChaCha20 is not defined
    decryptPassword https://vault.passky.org/js/default-functions.js:137
    <anonymous> https://vault.passky.org/js/post-passwords.js:5

Config:
- Debian, but the same phenomenon was also observed on Windows
- Browser: I tried firefox, chrome and chromium (with the same-ish results)

**Comment by zigazajc007** [comment]
Hello Passky clients 8.x.x are not compatible with Passky servers 7.x.x. This is because we moved from AES to XChaCha20 encryption and from SHA to Argon2id hash function.

If you want to access old server (7.x.x) https://eu1.passky.org make sure to also use old client (7.x.x) https://old.vault.passky.org.

I would suggest you to export your passwords from old account located on https://eu1.passky.org thru https://old.vault.passky.org, create new account on https://vault.passky.org (Make sure to select server on the new infrastructure ("Europe" or "America"))

![image](https://user-images.githubusercontent.com/44822563/208058911-2e4b843d-1d20-4221-be1f-47060d1df449.png)

and import all your passwords.
